#!/usr/bin/env bash
# A Bash script that runs nginx as user listening on all active IPs on port 8080 instead of port 80
pkill apache2
chmod -R 777 /etc/nginx/
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
